name: fast_travel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/hotels/
    - assets/files/

  fonts:
    - family: Anuphan
      fonts:
        - asset: assets/fonts/Anuphan-Thin.ttf
          weight: 100
        - asset: assets/fonts/Anuphan-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Anuphan-Light.ttf
          weight: 300
        - asset: assets/fonts/Anuphan-Regular.ttf
          weight: 400
        - asset: assets/fonts/Anuphan-Medium.ttf
          weight: 500
        - asset: assets/fonts/Anuphan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Anuphan-Bold.ttf
          weight: 700

    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/JosefinSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JosefinSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: italic
