// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKD2VxFWxijPDCPoMAZM3AcwM-Ns2ulVA',
    appId: '1:154441362266:web:e7b5c42e7a27fe62aba163',
    messagingSenderId: '154441362266',
    projectId: 'fast-travel-3e64c',
    authDomain: 'fast-travel-3e64c.firebaseapp.com',
    storageBucket: 'fast-travel-3e64c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Wa5VcPi38nFeD-ifDMP3WCJ5gmRTnqw',
    appId: '1:154441362266:android:219363ec4b54cbb4aba163',
    messagingSenderId: '154441362266',
    projectId: 'fast-travel-3e64c',
    storageBucket: 'fast-travel-3e64c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSOYjpzq_JhgFtASNifDlxgGuufvpVZdY',
    appId: '1:154441362266:ios:a418a5b63604e13daba163',
    messagingSenderId: '154441362266',
    projectId: 'fast-travel-3e64c',
    storageBucket: 'fast-travel-3e64c.firebasestorage.app',
    iosBundleId: 'com.example.fastTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSOYjpzq_JhgFtASNifDlxgGuufvpVZdY',
    appId: '1:154441362266:ios:a418a5b63604e13daba163',
    messagingSenderId: '154441362266',
    projectId: 'fast-travel-3e64c',
    storageBucket: 'fast-travel-3e64c.firebasestorage.app',
    iosBundleId: 'com.example.fastTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKD2VxFWxijPDCPoMAZM3AcwM-Ns2ulVA',
    appId: '1:154441362266:web:6fdb5e0b6438979eaba163',
    messagingSenderId: '154441362266',
    projectId: 'fast-travel-3e64c',
    authDomain: 'fast-travel-3e64c.firebaseapp.com',
    storageBucket: 'fast-travel-3e64c.firebasestorage.app',
  );
}
